-- 1. Table for Journals
CREATE TABLE IF NOT EXISTS journals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content TEXT NOT NULL,
  author_name TEXT,
  author_email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  last_edited_by TEXT,
  parent_id UUID REFERENCES journals(id),
  user_id UUID DEFAULT auth.uid()
);

-- 2. Table for Access Logs / Notifications
CREATE TABLE IF NOT EXISTS access_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_id UUID REFERENCES journals(id) ON DELETE CASCADE,
  visitor_name TEXT,
  visitor_email TEXT,
  visited_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  owner_id UUID -- To notify the correct owner
);

-- Enable Realtime for collaborative editing
ALTER PUBLICATION supabase_realtime ADD TABLE journals;

-- RLS (Row Level Security)
ALTER TABLE journals ENABLE ROW LEVEL SECURITY;
ALTER TABLE access_logs ENABLE ROW LEVEL SECURITY;

-- Journals Policies
CREATE POLICY "Anyone can read journals via link" ON journals FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create journals" ON journals FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update their own journals" ON journals FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own journals" ON journals FOR DELETE USING (auth.uid() = user_id);

-- Access Logs Policies
CREATE POLICY "Anyone can create access logs" ON access_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can view logs for their journals" ON access_logs FOR SELECT USING (auth.uid() = owner_id);
